services:
  - redis
  - docker
language: 
  - python
  - docker
python:
  - "3.7"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: docker-compose up

deploy:
  provider: heroku
  api_key:
    secure: "QmdZgM1+Ffpl+y0fUNvUdUDTE2j4suKzcGNxYMNrTGnb6N3drz8OWgHFRwVu8WvtgYbD/DHSFm3jM/FhYnRt8zLpqVbuTDBgGybFK3aYhbdmR4PSWW0bvV+Pq2BvHVvahmzzkCORz2pyQRSNyfbtlrfEGe2Egm3Kx2eCM55FdOKU5JuQKoCk3M6UzXD0r4eeCC5qghge5Q1AVlanpVHf/7t+xiAuS+Oo26rVFDR6bNOhJHcnAY27NOli3zc26asr4tDhuw9TeJJ2K0Q6j/wcp95PV06FZCDpZIku3owzlKL8zORo+YwozQhBILKNuDnga5hZ5vQghuZHeT0r3zmz59XazNDBWKeU2vS9Ow0dJSxU5dKF24sjcjBF9DixkcnQbuuDvZL/CVxLji71pK9CKKw5ZCvEJGOhxKmdYnDzDOLFE5MBK+UZcZ72U6b5KYz97SX6leq4au72wLMyL/r5j1WZsFCP78Nmqmworw9e/U7IH91Usrto3yv6mIEPXGsKOgB35eec4VY7tlKGBuGyxWKKfvJmwhrNDv3rlmUiovDUcbuIoCPaMURIb4h6EmqGXa7EAGNXq1c6knBsD+uRF4R/RFZauLeMuPLTuE9mpNHuqn8+y+a09ody3RnhNBM6yqXEAFsuHeeQVGybEEiz50BT3i01MmlLiXulq8PHf0U="
  app: love-my-movies
  on:
    repo: Danisnowman/love-my-movies

# services:
#   - redis
# language: python
# python: "3.7.3"
# env:  
#   global:
#     secure: M8+JvHzQX11oSeDMF2iiwH2JesKkCG5n9uvLbV/9oY8z7oG56sFqmwmAYl0WOwT6H6/t4VTQbNbIx5XA0Z0qWXp/7k+KUdi0X4iMU7JNZbYYcIvEPSmQTnecKl8yoc7piFI7H9gX9GruHqElyC71TZNT4Ff284n2cD3kVluRHU03S0qst1Nz9N+m8n+vpnbi3euS5PUCOwVc2hisKpuFLJxospYzI+9pmhd0R4tJES3bx0pVCIrd7u6BEVt8DGlk2imPK83RsLJry3TLBfp0sZ6wyhpAM/ey8AmWiuXQvylXcARhksCZP6V2WGFDIS63ZULdNv5cCCchqD2lo23fDdzgudrfiHG4ChU9evrv6akEzTYOtIJdInhBXkKW6Uj32YMiWBCDdvdVlw+P709/PvuIRYbQcnFaaep4nilQgJWBqZMjr4F0eFPqHs38bKLVmiJ3ZAYPVdZM3VidNimuoR60o769ZvLOJ8WQIvuErCmJCPwxE8Bfp+pGPwUrdYEAZ0FbzLRfpbqE7Nb7GVkYIBvHpvcOvedpHWNICoVvdL0bigIk619+n3TSk5O+2PJwPnIb8JkcJNP+Y7xdBArl7mqpaEpLKK3+U4M1OGFJaFzfHWlvEB/k5APJdNEsW7xOe/FJjAtw9aI0OGLeCo36g/kniLsLKrilcXpQcVXDiQo=
# install:
#   - pip install -r requirements.txt
# # command to run tests
# script:
#   - python app.py
